sudo: required
services:
    - docker

before_install:
    - docker build -t pablomendez95/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true pablomendez95/docker-react npm run test # the -e flag CI = true means to go back to the command line once tested

deploy:
    provider: elasticbeanstalk
    region: "eu-west-3"
    name: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-3-917851367860"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
