version: '3'
services:
    web: # First container for developing purposes
        stdin_open: true
        build: 
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes:
            - /app/node_modules # Do not try to map a folder app against app mpdules inside the container
            - .:/app
    tests: # Second container for testing purposes
        build: 
            context: . 
            dockerfile: Dockerfile.dev
        volumes: 
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"] # Overriding starting command